package com.teobaranga.kotlin.inject.viewmodel.sample.user

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import com.teobaranga.kotlin.inject.viewmodel.sample.SavedStateViewModelMap
import com.teobaranga.kotlin.inject.viewmodel.sample.ViewModelFactoryMap
import com.teobaranga.kotlin.inject.viewmodel.sample.ViewModelMap
import com.teobaranga.kotlin.inject.viewmodel.runtime.ContributesViewModel
import me.tatarka.inject.annotations.Provides
import software.amazon.lastmile.kotlin.inject.anvil.ContributesTo
import software.amazon.lastmile.kotlin.inject.anvil.ForScope
import software.amazon.lastmile.kotlin.inject.anvil.SingleIn
import kotlin.reflect.KClass

/**
 * Only used for testing in order to expose the 3 ViewModel maps generated by [ContributesViewModel] when
 * applied to various kinds of ViewModels.
 */
@ContributesTo(UserScope::class)
@SingleIn(UserScope::class)
interface UserViewModelMapComponent {

    /**
     * Map of simple ViewModel factories for ViewModels that have no assisted dependencies.
     */
    val viewModelMap: @ForScope(UserScope::class) ViewModelMap

    /**
     * Map of ViewModel factories that just require a [SavedStateHandle].
     */
    val savedStateViewModelMap: @ForScope(UserScope::class) SavedStateViewModelMap

    /**
     * Map of advanced ViewModel factories that require one or more assisted dependencies outside of [SavedStateHandle].
     */
    val viewModelFactoryMap: @ForScope(UserScope::class) ViewModelFactoryMap

    @Provides
    @SingleIn(UserScope::class)
    fun provideSimpleViewModelMap(
        map: Map<KClass<out ViewModel>, () -> ViewModel>
    ): @ForScope(UserScope::class) ViewModelMap = map

    @Provides
    @SingleIn(UserScope::class)
    fun provideSavedStateViewModelMap(
        map: Map<KClass<out ViewModel>, (SavedStateHandle) -> ViewModel>
    ): @ForScope(UserScope::class) SavedStateViewModelMap = map

    @Provides
    @SingleIn(UserScope::class)
    fun provideViewModelFactoryMap(
        map: Map<KClass<out ViewModel>, Any>
    ): @ForScope(UserScope::class) ViewModelFactoryMap = map
}
