package com.teobaranga.kotlin.inject.viewmodel.sample

import androidx.lifecycle.ViewModel
import com.teobaranga.kotlin.inject.viewmodel.runtime.ContributesViewModel
import me.tatarka.inject.annotations.Provides
import software.amazon.lastmile.kotlin.inject.anvil.AppScope
import software.amazon.lastmile.kotlin.inject.anvil.ContributesTo
import software.amazon.lastmile.kotlin.inject.anvil.ForScope
import software.amazon.lastmile.kotlin.inject.anvil.SingleIn
import kotlin.reflect.KClass

/**
 * Only used for testing in order to expose the 3 ViewModel maps generated by [ContributesViewModel] when
 * applied to various kinds of ViewModels.
 */
@ContributesTo(AppScope::class)
@SingleIn(AppScope::class)
interface AppViewModelMapComponent {

    /**
     * Map of simple ViewModel factories for ViewModels that have no assisted dependencies.
     */
    @ForScope(AppScope::class)
    val viewModelMap: ViewModelMap

    /**
     * Map of advanced ViewModel factories that require one or more assisted dependencies.
     */
    @ForScope(AppScope::class)
    val viewModelFactoryMap: ViewModelFactoryMap

    @Provides
    @SingleIn(AppScope::class)
    @ForScope(AppScope::class)
    fun provideSimpleViewModelMap(
        map: Map<KClass<out ViewModel>, () -> ViewModel>
    ): ViewModelMap = map

    @Provides
    @SingleIn(AppScope::class)
    @ForScope(AppScope::class)
    fun provideViewModelFactoryMap(
        map: Map<KClass<out ViewModel>, Any>
    ): ViewModelFactoryMap = map
}
